/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


 var assert = require('assert');
 const chai = require('chai');

 (function(root, factory) {
    if (typeof define === 'function' && define.amd) {
      // AMD.
      define(['expect.js', process.cwd()+'/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
      // CommonJS-like environments that support module.exports, like Node.
      factory(require('expect.js'), require(process.cwd()+'/src/index'));
    } else {
      // Browser globals (root is window)
      factory(root.expect, root.KindeReactNativeOAuth);
    }
  }(this, function(expect, KindeReactNativeOAuth) {
    'use strict';

    var instance;
  
    beforeEach(function() {
      instance = KindeReactNativeOAuth.KindeSDK;
    });
    describe('KindeSDK', function() {
      describe('new KindeSDK', function() {
        it('should instantiate ok', () => {
          expect(instance).to.be.ok;
        });
      
        it('should return instance of KindeSDK class', function() {
          const client = new instance('https://test.kinde.com', 'app://test.kinde.com/kinde_callback', 'PKCE', 'reg@live');
          chai.expect(client).to.be.an.instanceof(instance)
        });
      });
      describe('authorizationEndpoint', function() {
        it('should return same authorization endpoint', function() {
          const client = new instance('https://test.kinde.com', 'app://test.kinde.com/kinde_callback', 'PKCE', 'reg@live');
          assert.equal(client.authorizationEndpoint,'https://test.kinde.com/oauth2/auth')
        });
      });
      describe('tokenEndpoint', function() {
        it('should return same token endpoint', function() {
          const client = new instance('https://test.kinde.com', 'app://test.kinde.com/kinde_callback', 'PKCE', 'reg@live');
          assert.equal(client.tokenEndpoint,'https://test.kinde.com/oauth2/token')
        });
      });
      describe('logoutEndpoint', function() {
        it('should return same logout endpoint', function() {
          const client = new instance('https://test.kinde.com', 'app://test.kinde.com/kinde_callback', 'PKCE', 'reg@live');
          assert.equal(client.logoutEndpoint,'https://test.kinde.com/logout')
        });
      });
    });
  }));
  