/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

var assert = require('assert');
const chai = require('chai');

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.KindeReactNativeOAuth);
    }
})(this, function (expect, KindeReactNativeOAuth) {
    'use strict';

    var instance;

    beforeEach(function () {
        instance = KindeReactNativeOAuth.Utils;
    });
    describe('Utils', function () {
        describe('generateRandomString', function () {
            it('should return random string with 32 byte', function () {
                assert.equal(instance.generateRandomString().length, 43);
            });
        });
        describe('generateChallenge', function () {
            it('should return object challenge', function () {
                chai.assert.hasAllKeys(instance.generateChallenge(), [
                    'state',
                    'codeVerifier',
                    'codeChallenge'
                ]);
            });
        });
        describe('checkNotNull', function () {
            it('should return same instance', function () {
                assert.equal(instance.checkNotNull('test'), 'test');
            });
            it('should throw error', function () {
                assert.throws(() => instance.checkNotNull(null));
            });
        });
    });
});
