/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserIdentity from './UserIdentity';

/**
 * The CreateUser200Response model module.
 * @module model/CreateUser200Response
 * @version 1.1.0
 */
class CreateUser200Response {
    /**
     * Constructs a new <code>CreateUser200Response</code>.
     * @alias module:model/CreateUser200Response
     */
    constructor() {
        CreateUser200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>CreateUser200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUser200Response} obj Optional instance to populate.
     * @return {module:model/CreateUser200Response} The populated <code>CreateUser200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUser200Response();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(
                    data['created'],
                    'Boolean'
                );
            }
            if (data.hasOwnProperty('identities')) {
                obj['identities'] = ApiClient.convertToType(
                    data['identities'],
                    [UserIdentity]
                );
            }
        }
        return obj;
    }
}

/**
 * @member {String} id
 */
CreateUser200Response.prototype['id'] = undefined;

/**
 * @member {Boolean} created
 */
CreateUser200Response.prototype['created'] = undefined;

/**
 * @member {Array.<module:model/UserIdentity>} identities
 */
CreateUser200Response.prototype['identities'] = undefined;

export default CreateUser200Response;
