/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateUserRequestIdentitiesInner from './CreateUserRequestIdentitiesInner';
import CreateUserRequestProfile from './CreateUserRequestProfile';

/**
 * The CreateUserRequest model module.
 * @module model/CreateUserRequest
 * @version 0.0.1
 */
class CreateUserRequest {
    /**
     * Constructs a new <code>CreateUserRequest</code>.
     * @alias module:model/CreateUserRequest
     */
    constructor() {
        CreateUserRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>CreateUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserRequest} obj Optional instance to populate.
     * @return {module:model/CreateUserRequest} The populated <code>CreateUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserRequest();

            if (data.hasOwnProperty('profile')) {
                obj['profile'] = CreateUserRequestProfile.constructFromObject(
                    data['profile']
                );
            }
            if (data.hasOwnProperty('identities')) {
                obj['identities'] = ApiClient.convertToType(
                    data['identities'],
                    [CreateUserRequestIdentitiesInner]
                );
            }
        }
        return obj;
    }
}

/**
 * @member {module:model/CreateUserRequestProfile} profile
 */
CreateUserRequest.prototype['profile'] = undefined;

/**
 * @member {Array.<module:model/CreateUserRequestIdentitiesInner>} identities
 */
CreateUserRequest.prototype['identities'] = undefined;

export default CreateUserRequest;
