/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserIdentityResult model module.
 * @module model/UserIdentityResult
 * @version 0.0.1
 */
class UserIdentityResult {
    /**
     * Constructs a new <code>UserIdentityResult</code>.
     * @alias module:model/UserIdentityResult
     */
    constructor() {
        UserIdentityResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>UserIdentityResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserIdentityResult} obj Optional instance to populate.
     * @return {module:model/UserIdentityResult} The populated <code>UserIdentityResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserIdentityResult();

            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(
                    data['created'],
                    'Boolean'
                );
            }
            if (data.hasOwnProperty('identity_id')) {
                obj['identity_id'] = ApiClient.convertToType(
                    data['identity_id'],
                    'Number'
                );
            }
        }
        return obj;
    }
}

/**
 * @member {Boolean} created
 */
UserIdentityResult.prototype['created'] = undefined;

/**
 * @member {Number} identity_id
 */
UserIdentityResult.prototype['identity_id'] = undefined;

export default UserIdentityResult;
