/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserProfileV2 model module.
 * @module model/UserProfileV2
 * @version 0.0.1
 */
class UserProfileV2 {
    /**
     * Constructs a new <code>UserProfileV2</code>.
     * @alias module:model/UserProfileV2
     */
    constructor() {
        UserProfileV2.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>UserProfileV2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserProfileV2} obj Optional instance to populate.
     * @return {module:model/UserProfileV2} The populated <code>UserProfileV2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserProfileV2();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('provided_id')) {
                obj['provided_id'] = ApiClient.convertToType(
                    data['provided_id'],
                    'String'
                );
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('given_name')) {
                obj['given_name'] = ApiClient.convertToType(
                    data['given_name'],
                    'String'
                );
            }
            if (data.hasOwnProperty('family_name')) {
                obj['family_name'] = ApiClient.convertToType(
                    data['family_name'],
                    'String'
                );
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(
                    data['updated_at'],
                    'String'
                );
            }
        }
        return obj;
    }
}

/**
 * @member {String} id
 */
UserProfileV2.prototype['id'] = undefined;

/**
 * @member {String} provided_id
 */
UserProfileV2.prototype['provided_id'] = undefined;

/**
 * @member {String} name
 */
UserProfileV2.prototype['name'] = undefined;

/**
 * @member {String} given_name
 */
UserProfileV2.prototype['given_name'] = undefined;

/**
 * @member {String} family_name
 */
UserProfileV2.prototype['family_name'] = undefined;

/**
 * @member {String} updated_at
 */
UserProfileV2.prototype['updated_at'] = undefined;

export default UserProfileV2;
