/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserProfile from '../model/UserProfile';
import UserProfileV2 from '../model/UserProfileV2';

/**
 * OAuth service.
 * @module api/OAuthApi
 * @version 1.1.0
 */
export default class OAuthApi {
    /**
     * Constructs a new OAuthApi.
     * @alias module:api/OAuthApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Returns the details of the currently logged in user
     * Contains the id, names and email of the currently logged in user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserProfile} and HTTP response
     */
    getUserWithHttpInfo() {
        let postBody = null;

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['kindeBearerAuth'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = UserProfile;
        return this.apiClient.callApi(
            '/oauth2/user_profile',
            'GET',
            pathParams,
            queryParams,
            headerParams,
            formParams,
            postBody,
            authNames,
            contentTypes,
            accepts,
            returnType,
            null
        );
    }

    /**
     * Returns the details of the currently logged in user
     * Contains the id, names and email of the currently logged in user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserProfile}
     */
    async getUser() {
        const response = await this.getUserWithHttpInfo();
        return response.data;
    }

    /**
     * Returns the details of the currently logged in user
     * Contains the id, names and email of the currently logged in user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserProfileV2} and HTTP response
     */
    getUserProfileV2WithHttpInfo() {
        let postBody = null;

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['kindeBearerAuth'];
        let contentTypes = [];
        let accepts = ['application/json'];
        let returnType = UserProfileV2;
        return this.apiClient.callApi(
            '/oauth2/v2/user_profile',
            'GET',
            pathParams,
            queryParams,
            headerParams,
            formParams,
            postBody,
            authNames,
            contentTypes,
            accepts,
            returnType,
            null
        );
    }

    /**
     * Returns the details of the currently logged in user
     * Contains the id, names and email of the currently logged in user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserProfileV2}
     */
    async getUserProfileV2() {
        const response = await this.getUserProfileV2WithHttpInfo();
        return response.data;
    }
}
