/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import jwtDecode from 'jwt-decode';
import BaseStore from './base';
import KindeStorage from './KindeStorage';

/**
 * The Storage SDK module.
 * @module SDK/Storage
 * @version 1.1.0
 */

class Storage extends BaseStore {
    constructor() {
        super();
        this.storage = new KindeStorage();
    }

    async getToken() {
        const { password } = await this.storage.getItem();
        return password ? JSON.parse(password) : null;
    }

    async setToken(token) {
        return this.storage.setItem(token);
    }

    async getTokenType(type) {
        const token = await this.getToken();
        const newType = type === 'id_token' ? type : 'access_token';
        return token?.[newType] ?? null;
    }

    async getAccessToken() {
        return this.getTokenType('access_token');
    }

    async getIdToken() {
        return this.getTokenType('id_token');
    }

    async getExpiredAt() {
        const token = await this.getAccessToken();
        return token ? jwtDecode(token)['exp'] : 0;
    }

    getState() {
        return this.getItem('state');
    }

    setState(newState) {
        return this.setItem('state', this.convertString(newState));
    }

    getCodeVerifier() {
        return this.getItem('codeVerifier');
    }

    setCodeVerifier(newCodeVerifier) {
        return this.setItem(
            'codeVerifier',
            this.convertString(newCodeVerifier)
        );
    }

    getAuthStatus() {
        return this.getItem('authStatus');
    }

    setAuthStatus(newAuthStatus) {
        return this.setItem('authStatus', this.convertString(newAuthStatus));
    }

    async clearAll() {
        this.clear();
        return this.storage.clear();
    }

    async getUserProfile() {
        const token = await this.getIdToken();
        const payload = token ? jwtDecode(token) : {};
        return {
            id: payload['sub'] ?? '',
            given_name: payload['given_name'] ?? '',
            family_name: payload['family_name'] ?? '',
            email: payload['email'] ?? ''
        };
    }

    convertString(str) {
        return typeof str === 'string' ? str : JSON.stringify(str);
    }
}
const sessionStorage = (global.sessionStorage =
    global.sessionStorage ?? new Storage());

export default sessionStorage;
